// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs2y7_E_XlJbpuHLCWuZoIDbtyVsaTeHM',
    appId: '1:656873649584:android:f4d1ed9c9ab089f89d9275',
    messagingSenderId: '656873649584',
    projectId: 'pfa2-318ba',
    storageBucket: 'pfa2-318ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA44gTp2Y7D5610Tj1Rwsh2CkxcqZO2Q9U',
    appId: '1:656873649584:ios:2f8fbc4336ee12509d9275',
    messagingSenderId: '656873649584',
    projectId: 'pfa2-318ba',
    storageBucket: 'pfa2-318ba.appspot.com',
    iosClientId: '656873649584-mn3hcmfv8156piu5r0gbnog47r2s2ad8.apps.googleusercontent.com',
    iosBundleId: 'com.pfa.app',
  );
}
